### ISSUE TITLE
Email getting bounced

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/vassallandcoldharbour#48] opened 2015-09-29 08:14 UTC
Just got this back from a user. May be an issue with the mail forwarding etc.

Sue Bell (suebell@LIFEjourneys.co.uk) sent a message using the contact form
at http://www.vassallandcoldharbour.org.uk/contact.

I keep getting my email to vassal and coldharbour emails bounced when I reply
to your messages

Happy to go back to the user and ask more but I need to know what the process is of receiving emails etc from the outside to the VAC email address.

**Comment by pmackay** [comment] 2015-09-29 19:17
I think the problem is VAC has no mailbox. Options are:
- Create a gmail account or similar and use that instead of info@vassallandcoldharbour.org.uk for contacts.
- Setup gmail and try to make it pretend to be that info@ address.
- Setup a mailbox, but that might involve charges.

**Comment by pmackay** [comment] 2017-01-31 20:25
Closing but lets open again if a mailbox is needed.

**Closed as completed by pmackay** 2017-01-31 20:25 UTC
Labels: question, f-admin, p3-low

**Comment by djwesto** [comment] 2017-02-02 11:10
@pmackay Have you checked the email setup at CPN yet? If not I can fire off an email to Francis.

**Comment by pmackay** [comment] 2017-02-02 11:35
@djwesto no but the CPN site with correct domain isnt setup yet.
